name: frequenz-sdk-python

on: [pull_request, push, workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        python:
          - "3.8"
          - "3.9"
          - "3.10"
    runs-on: ${{ matrix.os }}

    steps:
      - name: Fetch sources
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('minimum-requirements-ci.txt', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-pip-

      - name: Install required Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install nox

      - name: run nox
        run: nox -e ci_checks_max pytest_min
        timeout-minutes: 10

  build-dist:
    runs-on: ubuntu-20.04
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install build dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U build

      - name: Build the source and binary distribution
        run: python -m build

      - name: Upload dist files
        uses: actions/upload-artifact@v3
        with:
          name: frequenz-sdk-python-dist
          path: dist/
          if-no-files-found: error

  publish-to-pypi:
    needs: ["test", "build-dist"]
    # Publish only on tags creation
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    steps:
      - name: Download dist files
        uses: actions/download-artifact@v3
        with:
          name: frequenz-sdk-python-dist

      - name: Publish the Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
